


CREATE DATABASE SISTEMAREPARACIONES

USE SISTEMAREPARACIONES


CREATE TABLE USUARIOS
(
    USUARIOID INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL,
    CORREOELECTRONICO VARCHAR(100) NOT NULL, 
    TELEFONO VARCHAR(20),
    CONSTRAINT UQ_USUARIOS_CORREO UNIQUE(CORREOELECTRONICO)
)


CREATE TABLE EQUIPOS
(
    EQUIPOID INT IDENTITY(1,1) PRIMARY KEY, 
    TIPOEQUIPO VARCHAR(20) NOT NULL,
    MODELO VARCHAR(30) NOT NULL,
    USUARIOID INT NOT NULL,
    CONSTRAINT FK_EQUIPOS_USUARIOS
    FOREIGN KEY (USUARIOID) REFERENCES USUARIOS(USUARIOID) 
)


CREATE TABLE TECNICOS 
(
    TECNICOID INT IDENTITY(1,1) PRIMARY KEY, 
    NOMBRE VARCHAR(50) NOT NULL,
    ESPECIALIDAD VARCHAR(30) 
)


CREATE TABLE REPARACIONES 
(
    REPARACIONID INT IDENTITY(1,1) PRIMARY KEY,
    EQUIPOID INT NOT NULL, 
    FECHASOLICITUD DATETIME NOT NULL,
    ESTADO VARCHAR (20), 
    CONSTRAINT FK_REPARACIONES_EQUIPOS 
    FOREIGN KEY(EQUIPOID) REFERENCES EQUIPOS(EQUIPOID)
)


CREATE TABLE ASIGNACIONES 
(
    ASIGNACIONID INT IDENTITY(1,1) PRIMARY KEY,
    REPARACIONID INT NOT NULL,
    TECNICOID INT NOT NULL, 
    FECHAASIGNACION DATETIME, 
    CONSTRAINT FK_ASIGNACIONES_REPARACIONES
    FOREIGN KEY(REPARACIONID) REFERENCES REPARACIONES(REPARACIONID),
    CONSTRAINT FK_ASIGNACIONES_TECNICOS
    FOREIGN KEY(TECNICOID) REFERENCES TECNICOS(TECNICOID) 
)


CREATE TABLE DETALLEREPARACION 
(
    DETALLEID INT IDENTITY(1,1) PRIMARY KEY,
    REPARACIONID INT NOT NULL, 
    DESCRIPCION VARCHAR(100), 
    FECHAINICIO DATETIME,
    FECHAFIN DATETIME, 
    CONSTRAINT FK_DETALLE_REPARACION
    FOREIGN KEY(REPARACIONID) REFERENCES REPARACIONES(REPARACIONID) 
)


INSERT INTO DBO.USUARIOS 
(NOMBRE, CORREOELECTRONICO, TELEFONO)
VALUES
('LUIS SALAZAR','LUISASR92@HOTMAIL.COM','89900635'),
('HELLEN RODRIGUEZ','HELLEN92@GMAIL.COM','86886984'),
('WENDY BARRANTES','WEN@YAHOO.NET','88601485'),
('ALONSO ALVARADO','ALONSO25@GMAIL.COM','73200159'),
('KEYLOR SALAZAR','KEYLORSA@GMAIL.COM','89987812');


INSERT INTO DBO.EQUIPOS
(TIPOEQUIPO, MODELO, USUARIOID)
VALUES
('LAPTOP','HP25510', 1),
('LAPTOP','APPLEMACBOOKPRO2', 2),
('LAPTOP','LENOVO82X700GCGJ', 3),
('CELULAR','HONOR8PRO2025', 4),
('TABLET','SAMSUNGS108825', 5);


INSERT INTO DBO.TECNICOS
(NOMBRE, ESPECIALIDAD) 
VALUES 
('JONATHAN RODRIGUEZ','REPARACION LAPTOPS'),
('ANA RICHMOND','MANTENIMIENTO PREVENTIVO'),
('JOSE JINESTA','REPARACION CELULARES'),
('ELENA ROJAS','EQUIPOS APPLE'),
('ERICK CARVAJAL','HARDWARE Y SOFTWARE');


INSERT INTO DBO.REPARACIONES
(EQUIPOID, FECHASOLICITUD, ESTADO)
VALUES
(1,'2026-07-01','FINALIZADO'),
(1,'2026-07-03','EN PROCESO'),
(1,'2026-07-04','PENDIENTE'),
(1,'2026-07-06','FINALIZADO'),
(1,'2026-07-10','EN PROCESO');



INSERT INTO DBO.ASIGNACIONES
(REPARACIONID, TECNICOID, FECHAASIGNACION)
VALUES
(1,1,'2026-07-01'),
(2,4,'2026-07-03'),
(3,4,'2026-07-04'),
(4,3,'2026-07-06'),
(5,5,'2026-07-10');


INSERT INTO DBO.DETALLEREPARACION
(REPARACIONID, DESCRIPCION, FECHAINICIO, FECHAFIN)
VALUES
(1,'CAMBIO DE PANTALLA DAÑADA','2026-07-01','2026-07-04'),
(2,'PROBLEMAS DE CONEXIONES','2026-07-03',NULL),
(3,'PASTA TERMICA Y CAMBIO DE TARJETA','2026-07-04',NULL),
(4,'BLOQUEADO POR INTRODUCIR PIN ERRONEO','2026-07-06','2026-07-07'),
(5,'ACTUALIZACION DE SOFTWARE','2026-07-10',NULL);

